import type { RuleTest } from '~/types'

export const ruleTestsCatala: RuleTest[] = [
  {
    id: 'prestagri-o-cas-2',
    ruleId: 'prestagri',
    label: 'Cas N°2 :',
    scenario: 'Cas N°2 :',
    inputs: {
      quotient_familial: '2500.00',
      nb_points: '12',
    },
    expected: '0.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-1',
    ruleId: 'prestagri',
    label: 'Cas N°1 : logement separe mais proche de l\'ecole',
    scenario: 'Cas N°1 : logement separe mais proche de l\'ecole',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '10',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '2',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-1',
    ruleId: 'prestagri',
    label: 'Cas N°1 : en etudes supérieure, au domicile parental un peu eloigne',
    scenario: 'Cas N°1 : en etudes supérieure, au domicile parental un peu eloigne',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '35',
      },
      'trajet_depuis_domicile_étudiant': 'Absent',
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': true,
    },
    expected: '3',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C3_éloignement_agent',
        value: '2',
      },
      {
        name: 'C5_études_supérieures',
        value: '1',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-2',
    ruleId: 'prestagri',
    label: 'Cas N°2 : en etudes supérieure mais au domicile des parents non eloigne',
    scenario: 'Cas N°2 : en etudes supérieure mais au domicile des parents non eloigne',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': 'Absent',
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': true,
    },
    expected: '0',
    expectedUnit: 'points',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-2',
    ruleId: 'prestagri',
    label: 'Cas N°2 : en etudes supérieure avec un loyer',
    scenario: 'Cas N°2 : en etudes supérieure avec un loyer',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '10',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': true,
    },
    expected: '3',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
      {
        name: 'C5_études_supérieures',
        value: '1',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-3',
    ruleId: 'prestagri',
    label: 'Cas N°3 : pas en etudes supérieure mais avec un loyer',
    scenario: 'Cas N°3 : pas en etudes supérieure mais avec un loyer',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '10',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '2',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-2',
    ruleId: 'prestagri',
    label: 'Cas N°2 : sans logement separe',
    scenario: 'Cas N°2 : sans logement separe',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': 'Absent',
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '0',
    expectedUnit: 'points',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-3',
    ruleId: 'prestagri',
    label: 'Cas N°3 : logement separe mais l\'adresse des parents est plus avantageuse',
    scenario: 'Cas N°3 : logement separe mais l\'adresse des parents est plus avantageuse',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '101',
        'durée_minutes': '50',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '10',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '4',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C3_éloignement_agent',
        value: '4',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-4',
    ruleId: 'prestagri',
    label: 'Cas N°4 : logement separe, l\'adresse des parents est moins avantageuse',
    scenario: 'Cas N°4 : logement separe, l\'adresse des parents est moins avantageuse',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '60',
        'durée_minutes': '50',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '32',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '4',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
      {
        name: 'C3_éloignement_étudiant',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-5',
    ruleId: 'prestagri',
    label: 'Cas N°5 : logement separe, l\'adresse des parents est aussi avantageuse (4 points)',
    scenario: 'Cas N°5 : logement separe, l\'adresse des parents est aussi avantageuse (4 points)',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '102',
        'durée_minutes': '50',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '32',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '4',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
      {
        name: 'C3_éloignement_étudiant',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-6',
    ruleId: 'prestagri',
    label: 'Cas N°6 : logement separe, l\'adresse des parents est aussi avantageuse (2 points)',
    scenario: 'Cas N°6 : logement separe, l\'adresse des parents est aussi avantageuse (2 points)',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '50',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '5',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '2',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-1',
    ruleId: 'prestagri',
    label: 'Cas N°1 : pas de matériel specifique',
    scenario: 'Cas N°1 : pas de matériel specifique',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': 'Absent',
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '0',
    expectedUnit: 'points',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-2',
    ruleId: 'prestagri',
    label: 'Cas N°2 : matériel spécifique supérieur au maximun eligible',
    scenario: 'Cas N°2 : matériel spécifique supérieur au maximun eligible',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': 'Absent',
      'montant_matériel_spécifique': '70.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '2',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C4_matériel',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-pt-cas-3',
    ruleId: 'prestagri',
    label: 'Cas N°3 : matériel spécifique inférieur au maximum eligible',
    scenario: 'Cas N°3 : matériel spécifique inférieur au maximum eligible',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': 'Absent',
      'montant_matériel_spécifique': '12.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '6/5',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C4_matériel',
        value: '6/5',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'prestagri-qf-cas-1',
    ruleId: 'prestagri',
    label: 'Cas N°1 :',
    scenario: 'Cas N°1 :',
    inputs: {
      famille: {
        personne_ou_enfant_porteur_handicap: false,
        'garde_alternée': false,
        'parent_isolé': false,
        outre_mer: false,
        membres_du_foyer: [
          {
            revenu_fiscal_reference: '12000.00',
            nombre_enfants: '0',
          },
          {
            revenu_fiscal_reference: '20600.00',
            nombre_enfants: '3',
          },
        ],
      },
    },
    expected: '543.33',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculQuotientFamilial',
    tags: [],
  },
  {
    id: 'prestagri-qf-cas-2',
    ruleId: 'prestagri',
    label: 'Cas N°2 :',
    scenario: 'Cas N°2 :',
    inputs: {
      famille: {
        personne_ou_enfant_porteur_handicap: false,
        'garde_alternée': false,
        'parent_isolé': true,
        outre_mer: false,
        membres_du_foyer: [
          {
            revenu_fiscal_reference: '32600.00',
            nombre_enfants: '3',
          },
        ],
      },
    },
    expected: '543.33',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculQuotientFamilial',
    tags: [],
  },
  {
    id: 'prestagri-qf-cas-3',
    ruleId: 'prestagri',
    label: 'Cas N°3 :',
    scenario: 'Cas N°3 :',
    inputs: {
      famille: {
        personne_ou_enfant_porteur_handicap: false,
        'garde_alternée': true,
        'parent_isolé': false,
        outre_mer: false,
        membres_du_foyer: [
          {
            revenu_fiscal_reference: '32600.00',
            nombre_enfants: '3',
          },
        ],
      },
    },
    expected: '603.70',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculQuotientFamilial',
    tags: [],
  },
  {
    id: 'prestagri-qf-cas-4',
    ruleId: 'prestagri',
    label: 'Cas N°4 :',
    scenario: 'Cas N°4 :',
    inputs: {
      famille: {
        personne_ou_enfant_porteur_handicap: false,
        'garde_alternée': false,
        'parent_isolé': false,
        outre_mer: true,
        membres_du_foyer: [
          {
            revenu_fiscal_reference: '12000.00',
            nombre_enfants: '3',
          },
          {
            revenu_fiscal_reference: '20600.00',
            nombre_enfants: '0',
          },
        ],
      },
    },
    expected: '434.67',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculQuotientFamilial',
    tags: [],
  },
]
