import type { RuleTest } from '~/types'

export const ruleTestsCatala: RuleTest[] = [
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '700.00',
      'ressources_ménage_arrondies': '36000.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-02-03',
      'nombre_personnes_à_charge': '3',
      situation_familiale_calcul_apl: 'Couple',
      zone: 'Zone1',
      logement_est_chambre: false,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '0.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '425.00',
      'ressources_ménage_arrondies': '11500.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-04-03',
      'nombre_personnes_à_charge': '2',
      situation_familiale_calcul_apl: 'Couple',
      zone: 'Zone2',
      logement_est_chambre: false,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '351.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '408.00',
      'ressources_ménage_arrondies': '14300.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-01-18',
      'nombre_personnes_à_charge': '3',
      situation_familiale_calcul_apl: 'PersonneSeule',
      zone: 'Zone3',
      logement_est_chambre: false,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '320.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '680.00',
      'ressources_ménage_arrondies': '39500.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-02-19',
      'nombre_personnes_à_charge': '1',
      situation_familiale_calcul_apl: 'Couple',
      zone: 'Zone1',
      logement_est_chambre: false,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '0.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '610.00',
      'ressources_ménage_arrondies': '2700.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-04-05',
      'nombre_personnes_à_charge': '0',
      situation_familiale_calcul_apl: 'PersonneSeule',
      zone: 'Zone1',
      logement_est_chambre: false,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '310.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '436.00',
      'ressources_ménage_arrondies': '19500.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-05-02',
      'nombre_personnes_à_charge': '0',
      situation_familiale_calcul_apl: 'Couple',
      zone: 'Zone2',
      logement_est_chambre: false,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '0.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '527.00',
      'ressources_ménage_arrondies': '32200.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-02-13',
      'nombre_personnes_à_charge': '6',
      situation_familiale_calcul_apl: 'Couple',
      zone: 'Zone2',
      logement_est_chambre: false,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '153.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '310.00',
      'ressources_ménage_arrondies': '14800.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-04-02',
      'nombre_personnes_à_charge': '0',
      situation_familiale_calcul_apl: 'Couple',
      zone: 'Zone1',
      logement_est_chambre: true,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '11.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
  {
    id: 'prestagri-o-cas-tests',
    ruleId: 'prestagri',
    label: 'Tests',
    scenario: 'Tests',
    inputs: {
      'loyer_principal#base': '400.00',
      'ressources_ménage_arrondies': '7800.00',
      'bénéficiaire_aide_adulte_ou_enfant_handicapés': false,
      date_courante: '2022-06-10',
      'nombre_personnes_à_charge': '0',
      situation_familiale_calcul_apl: 'PersonneSeule',
      zone: 'Zone1',
      logement_est_chambre: false,
      'âgées_ou_handicap_adultes_hébergées_onéreux_particuliers': false,
      type_aide: 'AidePersonnaliséeLogement',
      colocation: false,
      'réduction_loyer_solidarité': '0.00',
      'logement_meublé_d842_2': false,
      'résidence': 'Métropole',
    },
    expected: '210.00',
    expectedUnit: 'EUR',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'Trace Catala (interpréteur, calcul réel)',
    engineVersion: 'catala (non renseigné)',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAidePersonnaliséeLogementLocatif',
    tags: [],
  },
]
