import type { RuleTest } from '~/types'

export const ruleTestsCatala: RuleTest[] = [
  {
    id: 'aide-scolarite-cas-2',
    ruleId: 'prestagri',
    label: 'Cas N°2 :',
    scenario: 'Cas N°2 :',
    inputs: {
      quotient_familial: '2500.00',
      nb_points: '12',
    },
    expected: '0.00',
    expectedUnit: 'points',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'TO BE VALIDATED',
    engineVersion: 'catala 1.2.1',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculAideScolarite',
    tags: [],
  },
  {
    id: 'aide-scolarite-cas-1',
    ruleId: 'prestagri',
    label: 'Cas N°1 : logement separe mais proche de l\'ecole',
    scenario: 'Cas N°1 : logement separe mais proche de l\'ecole',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '10',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '2',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'TO BE VALIDATED',
    engineVersion: 'catala 1.2.1',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'aide-scolarite-cas-2',
    ruleId: 'prestagri',
    label: 'Cas N°2 : sans logement separe',
    scenario: 'Cas N°2 : sans logement separe',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '10',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': 'Absent',
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '0',
    expectedUnit: 'points',
    expectedCriteria: [],
    source: 'administration',
    status: 'valide',
    validatedBy: 'TO BE VALIDATED',
    engineVersion: 'catala 1.2.1',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'aide-scolarite-cas-3',
    ruleId: 'prestagri',
    label: 'Cas N°3 : logement separe mais l\'adresse des parents est plus avantageuse',
    scenario: 'Cas N°3 : logement separe mais l\'adresse des parents est plus avantageuse',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '101',
        'durée_minutes': '50',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '10',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '4',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C3_éloignement_agent',
        value: '4',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'TO BE VALIDATED',
    engineVersion: 'catala 1.2.1',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'aide-scolarite-cas-4',
    ruleId: 'prestagri',
    label: 'Cas N°4 : logement separe, l\'adresse des parents est moins avantageuse',
    scenario: 'Cas N°4 : logement separe, l\'adresse des parents est moins avantageuse',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '60',
        'durée_minutes': '50',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '32',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '4',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
      {
        name: 'C3_éloignement_étudiant',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'TO BE VALIDATED',
    engineVersion: 'catala 1.2.1',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'aide-scolarite-cas-5',
    ruleId: 'prestagri',
    label: 'Cas N°5 : logement separe, l\'adresse des parents est aussi avantageuse (4 points)',
    scenario: 'Cas N°5 : logement separe, l\'adresse des parents est aussi avantageuse (4 points)',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '102',
        'durée_minutes': '50',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '32',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '4',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
      {
        name: 'C3_éloignement_étudiant',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'TO BE VALIDATED',
    engineVersion: 'catala 1.2.1',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
  {
    id: 'aide-scolarite-cas-6',
    ruleId: 'prestagri',
    label: 'Cas N°6 : logement separe, l\'adresse des parents est aussi avantageuse (2 points)',
    scenario: 'Cas N°6 : logement separe, l\'adresse des parents est aussi avantageuse (2 points)',
    inputs: {
      trajet_depuis_domicile_agent: {
        distance_km: '50',
        'durée_minutes': '20',
      },
      'trajet_depuis_domicile_étudiant': {
        'Présent': {
          distance_km: '5',
          'durée_minutes': '20',
        },
      },
      'montant_matériel_spécifique': '0.00',
      valeur_point: '10.00',
      'étudiant_en_filière_post_bac': false,
    },
    expected: '2',
    expectedUnit: 'points',
    expectedCriteria: [
      {
        name: 'C2_domiciliation_séparée',
        value: '2',
      },
    ],
    source: 'administration',
    status: 'valide',
    validatedBy: 'TO BE VALIDATED',
    engineVersion: 'catala 1.2.1',
    nativeFormat: 'catala-assert',
    nativeRef: 'aide_scolarite.catala_fr#CalculPointsAideScolarite',
    tags: [],
  },
]
